export interface Race {
  meetingKey: string
  meetingName: string
  country: string
  location: string
  circuitKey: string
  round: number
  dateStart: string
  dateEnd: string
  dateDisplay: string
}

// 2025 F1 Calendar (placeholder data - will be fetched from OpenF1 API)
export const races2025: Race[] = [
  {
    meetingKey: "1242",
    meetingName: "Australian Grand Prix",
    country: "Australia",
    location: "Melbourne",
    circuitKey: "albert_park",
    round: 1,
    dateStart: "2025-03-14",
    dateEnd: "2025-03-16",
    dateDisplay: "Mar 14-16",
  },
  {
    meetingKey: "1243",
    meetingName: "Chinese Grand Prix",
    country: "China",
    location: "Shanghai",
    circuitKey: "shanghai",
    round: 2,
    dateStart: "2025-03-21",
    dateEnd: "2025-03-23",
    dateDisplay: "Mar 21-23",
  },
  {
    meetingKey: "1244",
    meetingName: "Japanese Grand Prix",
    country: "Japan",
    location: "Suzuka",
    circuitKey: "suzuka",
    round: 3,
    dateStart: "2025-04-04",
    dateEnd: "2025-04-06",
    dateDisplay: "Apr 4-6",
  },
  {
    meetingKey: "1245",
    meetingName: "Bahrain Grand Prix",
    country: "Bahrain",
    location: "Sakhir",
    circuitKey: "bahrain",
    round: 4,
    dateStart: "2025-04-11",
    dateEnd: "2025-04-13",
    dateDisplay: "Apr 11-13",
  },
  {
    meetingKey: "1246",
    meetingName: "Saudi Arabian Grand Prix",
    country: "Saudi Arabia",
    location: "Jeddah",
    circuitKey: "jeddah",
    round: 5,
    dateStart: "2025-04-18",
    dateEnd: "2025-04-20",
    dateDisplay: "Apr 18-20",
  },
  {
    meetingKey: "1247",
    meetingName: "Miami Grand Prix",
    country: "United States",
    location: "Miami",
    circuitKey: "miami",
    round: 6,
    dateStart: "2025-05-02",
    dateEnd: "2025-05-04",
    dateDisplay: "May 2-4",
  },
  {
    meetingKey: "1248",
    meetingName: "Emilia Romagna Grand Prix",
    country: "Italy",
    location: "Imola",
    circuitKey: "imola",
    round: 7,
    dateStart: "2025-05-16",
    dateEnd: "2025-05-18",
    dateDisplay: "May 16-18",
  },
  {
    meetingKey: "1249",
    meetingName: "Monaco Grand Prix",
    country: "Monaco",
    location: "Monte Carlo",
    circuitKey: "monaco",
    round: 8,
    dateStart: "2025-05-23",
    dateEnd: "2025-05-25",
    dateDisplay: "May 23-25",
  },
  {
    meetingKey: "1250",
    meetingName: "Spanish Grand Prix",
    country: "Spain",
    location: "Barcelona",
    circuitKey: "barcelona",
    round: 9,
    dateStart: "2025-05-30",
    dateEnd: "2025-06-01",
    dateDisplay: "May 30 - Jun 1",
  },
  {
    meetingKey: "1251",
    meetingName: "Canadian Grand Prix",
    country: "Canada",
    location: "Montreal",
    circuitKey: "montreal",
    round: 10,
    dateStart: "2025-06-13",
    dateEnd: "2025-06-15",
    dateDisplay: "Jun 13-15",
  },
  {
    meetingKey: "1252",
    meetingName: "Austrian Grand Prix",
    country: "Austria",
    location: "Spielberg",
    circuitKey: "red_bull_ring",
    round: 11,
    dateStart: "2025-06-27",
    dateEnd: "2025-06-29",
    dateDisplay: "Jun 27-29",
  },
  {
    meetingKey: "1253",
    meetingName: "British Grand Prix",
    country: "Great Britain",
    location: "Silverstone",
    circuitKey: "silverstone",
    round: 12,
    dateStart: "2025-07-04",
    dateEnd: "2025-07-06",
    dateDisplay: "Jul 4-6",
  },
  {
    meetingKey: "1254",
    meetingName: "Belgian Grand Prix",
    country: "Belgium",
    location: "Spa-Francorchamps",
    circuitKey: "spa",
    round: 13,
    dateStart: "2025-07-25",
    dateEnd: "2025-07-27",
    dateDisplay: "Jul 25-27",
  },
  {
    meetingKey: "1255",
    meetingName: "Hungarian Grand Prix",
    country: "Hungary",
    location: "Budapest",
    circuitKey: "hungaroring",
    round: 14,
    dateStart: "2025-08-01",
    dateEnd: "2025-08-03",
    dateDisplay: "Aug 1-3",
  },
  {
    meetingKey: "1256",
    meetingName: "Dutch Grand Prix",
    country: "Netherlands",
    location: "Zandvoort",
    circuitKey: "zandvoort",
    round: 15,
    dateStart: "2025-08-29",
    dateEnd: "2025-08-31",
    dateDisplay: "Aug 29-31",
  },
  {
    meetingKey: "1257",
    meetingName: "Italian Grand Prix",
    country: "Italy",
    location: "Monza",
    circuitKey: "monza",
    round: 16,
    dateStart: "2025-09-05",
    dateEnd: "2025-09-07",
    dateDisplay: "Sep 5-7",
  },
  {
    meetingKey: "1258",
    meetingName: "Azerbaijan Grand Prix",
    country: "Azerbaijan",
    location: "Baku",
    circuitKey: "baku",
    round: 17,
    dateStart: "2025-09-19",
    dateEnd: "2025-09-21",
    dateDisplay: "Sep 19-21",
  },
  {
    meetingKey: "1259",
    meetingName: "Singapore Grand Prix",
    country: "Singapore",
    location: "Marina Bay",
    circuitKey: "singapore",
    round: 18,
    dateStart: "2025-10-03",
    dateEnd: "2025-10-05",
    dateDisplay: "Oct 3-5",
  },
  {
    meetingKey: "1260",
    meetingName: "United States Grand Prix",
    country: "United States",
    location: "Austin",
    circuitKey: "cota",
    round: 19,
    dateStart: "2025-10-17",
    dateEnd: "2025-10-19",
    dateDisplay: "Oct 17-19",
  },
  {
    meetingKey: "1261",
    meetingName: "Mexico City Grand Prix",
    country: "Mexico",
    location: "Mexico City",
    circuitKey: "mexico",
    round: 20,
    dateStart: "2025-10-24",
    dateEnd: "2025-10-26",
    dateDisplay: "Oct 24-26",
  },
  {
    meetingKey: "1262",
    meetingName: "São Paulo Grand Prix",
    country: "Brazil",
    location: "São Paulo",
    circuitKey: "interlagos",
    round: 21,
    dateStart: "2025-11-07",
    dateEnd: "2025-11-09",
    dateDisplay: "Nov 7-9",
  },
  {
    meetingKey: "1263",
    meetingName: "Las Vegas Grand Prix",
    country: "United States",
    location: "Las Vegas",
    circuitKey: "las_vegas",
    round: 22,
    dateStart: "2025-11-20",
    dateEnd: "2025-11-22",
    dateDisplay: "Nov 20-22",
  },
  {
    meetingKey: "1264",
    meetingName: "Qatar Grand Prix",
    country: "Qatar",
    location: "Lusail",
    circuitKey: "lusail",
    round: 23,
    dateStart: "2025-11-28",
    dateEnd: "2025-11-30",
    dateDisplay: "Nov 28-30",
  },
  {
    meetingKey: "1265",
    meetingName: "Abu Dhabi Grand Prix",
    country: "Abu Dhabi",
    location: "Yas Marina",
    circuitKey: "yas_marina",
    round: 24,
    dateStart: "2025-12-05",
    dateEnd: "2025-12-07",
    dateDisplay: "Dec 5-7",
  },
]
